### ISSUE TITLE
Is the parser only for english script ? 

### ISSUE THREAD

**Issue by Ynohtna-Fr** [mattrichmo/ScreenBaby#1]
Hi ! 
I'm currently working on a web app to give AD better tools for their job.

When I'm passing a French script, well structured, the parser doesn't seem's to work. Here is what I get : 

`{
  scriptTitle: 'AVANT NOS CENDRES',
  scriptAuthor: [],
  scenes: [],
  cast: [],
  docMeta: {
    numPages: 0,
    numLines: 0,
    numCharacters: 0,
    numProps: 0,
    numDialogueLines: 0
  }
}
`

Do you have any idea what's wrong ? And is the project still on ? 

Thanks !

**Comment by mattrichmo** [comment]
Unfortunately yes it's English only for now but it shouldn't be too hard to change it to another language by switching the regex around to include French versions as well. 

Unfortunately, I've moved on from this project and am developing v2 but it's not nearly ready to be shown yet. Thanks for the heads up though, will try to be more accommodating for additional languages in the future.

**Comment by Ynohtna-Fr** [comment]
All right ty for your answer. I'm thrilled to see the upcomming v2 !
